config/routes.rb
Livinlog::Application.routes.draw do
  resources :relationships

  resources :logs

  resources :users

  root to: 'users#new'

  get "sessions/new"
  post "sessions/create"
  get "sessions/destroy"

  get 'buddies', to: 'users#buddies', as: 'buddies'

end

app/models/log.rb
class Log < ActiveRecord::Base

	default_scope order: 'created_at DESC'
	belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
belongs_to :follower, class_name: "User"
belongs_to :followed, class_name: "User"


	
end

app/models/user.rb
class User < ActiveRecord::Base
 before_validation :prep_email
 before_save :create_avatar_hash
	has_secure_password
	has_many :follower_relationships, class_name: "Relationship", foreign_key: "followed_id"
  has_many :followed_relationships, class_name: "Relationship", foreign_key: "follower_id"

  has_many :followers, through: :follower_relationships
  has_many :followeds, through: :followed_relationships
  has_many :logs

 	validates :name, presence: true
 	validates :username, uniqueness: true, presence: true
 	validates :email, uniqueness: true, presence: true

def following? user
    self.followeds.include? user
end
 
def follow user
    Relationship.create follower_id: self.id, followed_id: user.id
end



private
 
def prep_email
    self.email = self.email.strip.downcase if self.email
end
def create_avatar_hash
    self.avatar_hash = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email)}?s=50"
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
 
	helper_method :current_user

  
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController

def index
	@logs = Log.all
	@log = Log.new
end
def new
    @log = Log.new
end
def show
    @log = Log.find(params[:id])
end
def edit
    @log = Log.find(params[:id])
end
def create
    @log = Log.new(log_params)
    @log.user_id = current_user.id
   
    if @log.save
        redirect_to current_user 
    else
        flash[:error] = "Problem!"
        redirect_to current_user
    end
end

def update
    @log = Log.find(params[:id])
    if @log.update(log_params)
        redirect_to @log, notice: 'Log was successfully updated.'
    else
        render action: 'edit'
    end
end
def destroy
    @log = Log.find(params[:id])
    @log.destroy
    redirect_to logs_url

end

private

	def log_params
		params.require(:log).permit(:when, :address, :address_2, :city, :state, :zip, :title, :description, :media_type, :category, :latitude, :longitude)
	end




end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
		def create
            @relationship = Relationship.new
            @relationship.followed_id = params[:followed_id]
            @relationship.follower_id = current_user.id
     
        if @relationship.save
            redirect_to User.find params[:followed_id]
        else
            flash[:error] = "Couldn't Follow"
            redirect_to root_url
        end
		end
    def destroy
        @relationship = Relationship.find(params[:id])
        @relationship.destroy
        redirect_to users_path(@relationship.followed_id)
    end




end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	 user = User.find_by_username(params[:username])
	    if user && user.authenticate(params[:password])
	        session[:user_id] = user.id
	        redirect_to root_url, notice: "Logged in!"
	    else
	        flash[:error] = "Wrong Username or Password."
	        redirect_to root_url
	    end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, notice: "Logged out."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def new
		
    if current_user
        redirect_to buddies_path
    else
        @user = User.new
    end
	
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to @user, notice: "Thank you for signing up for LivinLog!"
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
		@log = Log.new
		@relationship = Relationship.where(
		    follower_id: current_user.id,
		    followed_id: @user.id
		).first_or_initialize if current_user



	end
	def buddies
	    if current_user
	        @log = Log.new
	        buddies_ids = current_user.followeds.map(&:id).push(current_user.id)
	        @logs = Log.find_all_by_user_id buddies_ids
	    else
	        redirect_to root_url
	    end
	end







	private

	def user_params
		params.require(:user).permit(:avatar_hash, :username, :name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Livinlog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<nav class='navbar navbar-default' role="navigation">
  <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
 <div class="collapse navbar-collapse navbar-ex1-collapse">
    <a class='navbar-brand' href='/'>LivinLog</a>
    <ul class="nav navbar-nav">
      <li>
      </li>
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to "Libraries", users_path %></li>
				<li><%= link_to logs_path do %>
            <span class="glyphicon glyphicon-th"></span> Logs <% end %>
        </li>
        <li class="dropdown"> 
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="glyphicon glyphicon-plus"></span> New </a>
              <ul class='dropdown-menu'>
                <li><%= link_to "New Log", new_log_path %>
                </li>
              </ul>
            </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span><%=current_user.name %></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "My Profile", current_user %></li>
                <li><%= link_to "Log Out", sessions_destroy_path %></li>
              </ul>
  
      <% else %>
      <li class="form-group"><%= form_tag sessions_create_path do %>
        <span><%= text_field_tag :username, nil, placeholder: "username", class: "form-nav" %></span>
        <span><%= password_field_tag :password, nil, placeholder: "password", class: 'form-nav' %><span>
        <span><%= submit_tag "Log In", class: "btn btn-default" %></span></li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>
  </nav>
  <div class='container'>
    <div class="row">
        <% flash.each do |name, msg| %>
            <%= content_tag :div, msg, class: "flash #{name}" %>
        <% end %>
        <%= yield %>
    </div>
  </div>
  <footer>
    
  </footer>
</body>
</html>

app/views/logs/_form.html.erb
<%= form_for @log do |f| %>
  <% if @log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>
      <ul>
      <% @log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
        <%= f.text_field :when, placeholder: "Date", class: 'form-control' %>
  </div>
  <div class="form-group">
        <%= f.text_field :address, placeholder: "Address", class: 'form-control' %>
  </div>
  <div class="form-group">
        <%= f.text_field :address_2, placeholder: "Address 2", class: 'form-control' %>
  </div>
  <div class="form-group">
        <%= f.text_field :city, placeholder: "City", class: 'form-control' %>
  </div>
  <div class="form-group">
        <%= f.text_field :state, placeholder: "State", class: 'form-control' %>
  </div>
  <div class="form-group">
        <%= f.text_field :zip, placeholder: "Zip", class: 'form-control' %>
  </div>
  <div class="form-group">
        <%= f.text_field :title, placeholder: "Title", class: 'form-control' %>
  </div>
  <div class="form-group">
        <%= f.text_field :media_type, placeholder: "Media Type", class: 'form-control' %>
  </div>
  <div class="form-group">
        <%= f.text_field :category, placeholder: "Category", class: 'form-control' %>
  </div>
  <div class="form-group">
        <%= f.text_area :description, placeholder: "Description", class: 'form-control' %>
  </div>
  <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
  </div>
      <% end %>

app/views/logs/edit.html.erb
<h1>Editing log</h1>

<%= render 'form' %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<% if current_user %>
<h3 class="panel-title">Public Logs</h3>
<div id="logs" class="transitions-enabled">
  <% @logs.each do |log| %>
  <div class="box panel panel-default">
    <div class="panel-body">
      <p><%= log.title %></p>
      <p><%= log.description %></p>
      <p><a href="<%= user_path log.user %>">
        <span class="name"><%= log.user.name %></span></a>
        <span class="spacing"> @<%= log.user.username %></span>
      </p>
      <%= link_to 'Show', log_path(log) %>
      <% if log.user == current_user %>
        <%= link_to 'Edit', edit_log_path(log) %>
        <%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
    </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/logs/new.html.erb
<h1>New log</h1>

<%= render 'form' %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<%= link_to 'Back', logs_path %>
<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">
			</div>
			<div class="panel-body">
				<p><%= simple_format @log.description %></p>
					<a href="<%= user_path @log.user %>">
            <span class="name"><%= @log.user.name %></span>
            </a>
            @<%= @log.user.username %></br>
            <% if @log.user == current_user %>
							<%= link_to edit_log_path(@log) do %><span class="glyphicon glyphicon-edit"></span> Edit
							<% end %>
        			<%= link_to log_path, method: :delete, data: { confirm: 'Are you sure?' } do %>
          			<span class="glyphicon glyphicon-trash"></span> Delete
         			 <% end %>
         			<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/buddies.html.erb
<% if current_user %>
<h3 class="panel-title">Log Feed</h3>
<div id="logs" class="transitions-enabled">
  <% @logs.each do |log| %>
  <div class="box panel panel-default">
    <div class="panel-body">
        <p><%= log.title %> </p>
        <p><%= log.description %></p>
        <p><a href="<%= user_path log.user %>">
          <span class="name"><%= log.user.name %></span>
          </a><span class="spacing"> @<%= log.user.username %></span>
        </p>
  <%= link_to 'Show', log_path(log) %>
      <% if log.user == current_user %>
        <%= link_to 'Edit', edit_log_path(log) %>
        <%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
    </div>
  </div>
  <% end %>
</div>
  <% end %>

app/views/users/index.html.erb
<% if current_user %>
<h3 class="panel-title">Libraries</h3>
<div id="logs" class="trasitions-enabled">
  <% @users.each do |user| %>
  <div class="box panel panel-default">
    <div class="panel-body">
      <p><img id="avatar" src='<%= user.avatar_hash %>'><a href="<%= user_path user %>"><%= user.name %></a>  
  	</div>
  </div>
  	<% end %>
  </div>
  <% end %>

app/views/users/new.html.erb
<div class="jumbotron">
  <div class="input-group">
    <h1>New to LivinLog?<br>
      <small>Sign up</small></h1>
      <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= f.text_field :email, placeholder: "email" %><br>
        <%= f.text_field :username, placeholder: "username" %><br>
        <%= f.text_field :name, placeholder: "name" %><br>
        <%= f.password_field :password, placeholder: "password" %><br>
        <%= f.password_field :password_confirmation, placeholder: "password confirmation" %><br>
        <%= f.submit "Create Account" %>
    <% end %>
  </div>
 
</div>

app/views/users/show.html.erb
<% if current_user %>
<img class="avatar" src='<%= @user.avatar_hash %>'>
<span><strong><%= @user.name %> </span> @<%= @user.username %></strong>

<p><%= @user.logs.size %> Logs
<span class="spacing"><%= @user.followers.count %> Followers</span>
<span class="spacing"> <%= @user.followeds.count %> Following</span>
</p>
<% if current_user && @user != current_user %>
  <% if current_user.following? @user %>
    <%= form_tag relationship_path(@relationship), method: :delete do %>
    <%= submit_tag "Unfollow" %>
    <% end %>
  <% else %>
    <%= form_for @relationship do %>
    <%= hidden_field_tag :followed_id, @user.id %>
    <%= submit_tag "Follow" %>
    <% end %>
  <% end %>
<% end %>


<h3>Logs</h3>
<div id="logs" class="transitions-enabled">
  <% @user.logs.each do |log| %>
  <div class="box panel panel-default">
    <div class="panel-body">
      <p><%= log.title %></p>
        <p><%= log.description %> </p>
        <p><a href="<%= user_path log.user %>">
        <span class="name"><%= @user.name %></span></a>
        <span class="spacing"> @<%= @user.username %></span>
      </p>
    
    <%= link_to 'Show', log_path(log) %>
      <% if log.user == current_user %>
        <%= link_to 'Edit', edit_log_path(log) %>
        <%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      
    </div>
  </div>
<% end %>
</div>
 <% end %>